CREATE DATABSE; Escola

CREATE TABLE Alunos (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	idade INT NOT NULL,
	email VARCHAR(100) NOT NULL
);

CREATE TABLE Professores (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	idade INT NOT NULL,
	email VARCHAR(100) NOT NULL
);
	CREATE TABLE cursos (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	curso VARCHAR(100) NOT NULL
	);
	
	CREATE TABLE HORARIOS (
	id INT PRIMARY KEY AUTO_INCREMENT,
	HORARIO VARCHAR(100) NOT NULL,
	DIA VARCHAR(100) NOT NULL
	);
