a = input('digite algo: ')
print("O tipo primitivo desse valor é ", type(a))
print("só tem espaço: ", a.isspace())
print("é alfábetico? ", a.isalpha())
print("é alfanúmerico? ", a.isalpha())
print("é númerico? " , a.isnumeric())
print("está em maiscula? ", a.isupper())
print("está em minuscula? ", a.islower())
print("está capitalizada? ", a.istitle())
